### ISSUE TITLE
Include notfound.org in the 404 template?

### ISSUE THREAD

**Issue by silverhook** [talha131/pelican-elegant#161]
I recently stumbled upon this page <http://notfound.org/>, which is ingeniously making use of the 404 error pages by embedding lost people posters into it. I really like this concept.

@talha131 and users of Pelican Elegant, do you think we should build this into the 404 template by default or rather let everyone do it manually themselves?

**Comment by talha131** [comment]
I don't think it should be added to the theme. People who like the idea can add it in their fork.

**Comment by silverhook** [comment]
Sounds fair.

I’ll close it as WONTFIX.
